try {

} catch {
    console.log(1);
}